# Using our Enviroment

Before using our custom enviroment we must use pip to install it.

In [3]:
!pip install --upgrade --editable gym-env

Obtaining file:///E:/Abhinav/CS698R_DRL/Foraging%20in%20Replenishing%20Patches/gym-env
  Attempting uninstall: gym-env
    Found existing installation: gym-env 1.0.0
    Uninstalling gym-env-1.0.0:
      Successfully uninstalled gym-env-1.0.0
  Running setup.py develop for gym-env


It's better to restart the kernel once the pip is done installing.

We now simply import gym, create our environment and run a few steps.

In [7]:
import gym
import gym_env

import numpy as np

env = gym.make('foraging-replenishing-patches-v0')

env.reset()
for _ in range(10):
    action = np.random.randint(9)
    state, reward, done, _ = env.step(action)
    print(action, state, reward, done)
    if done:
        break

    

2 2 0 False
1 1 0 False
5 5 0 False
3 3 0 False
0 0 0 False
6 6 0 False
self.current_state: 6
[0 4 4 0 4 0 0 0]
[ 0 74 74  0 74  0 70  0]
8 6 63.0 False
self.current_state: 6
[0 4 4 0 4 0 0 0]
[ 0 78 78  0 78  0 63  0]
8 6 119.7 False
5 5 119.7 False
0 0 119.7 False
